server:
    port: 8770
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#        \配置git仓库位置
          uri: https://gitee.com/""/basicJava/
#配置仓库路径下的相对搜索位置，可以配置多个
          search-paths: config-repo
          username: ""
          password: yu718580
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: false
management:
  security:
    enabled: false