
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: useradmin
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/xixiu-work
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 1000
    max-idle: 100
    #HikariCP连接池设置，同样的条件下，页面查询响应速度提高20%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      allow-pool-suspension: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 5
management:
#refresh请求的跟路径
  context-path: /
  security:
#  通过refresh post请求时不会报HTTP（401）
    enabled: false
username2: johnwa8888
