server:
  port: 8761
spring:
  application:
    name: useradmin
  redis:
    host: 211.159.185.172
    password: yu718580
  datasource:
#    url: jdbc:mysql://localhost:3306/rbac?useUnicode=yes&characterEncode=utf-8&useSSL=false
    url: jdbc:mysql://211.159.185.172:3306/activiti?useUnicode=yes&characterEncode=utf-8&useSSL=false
    username: root
    password: yu718580
    driver-class-name: com.mysql.jdbc.Driver
    #HikariCP连接池设置，同样的条件下，页面查询响应速度提高20%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      allow-pool-suspension: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 10000
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 30000

# mybatis配置
mybatis:
  type-aliases-package: com.john.auth.domain.entity
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 10000
    #下划线匹配驼峰
    map-underscore-to-camel-case: true

imooc:
  security:
    browser:
      loginPage: /security/needlogin

name: bbb
auth:
  permits: /hello,/auth/needlogin,/auth/piccaptcha,/auth/token,/favicon.ico,/**
security:
  basic:
    enabled: false
